"""
The for keyword on its own, irrespective of any particular practical use.
The for loop can iterate through the values in any Sequence data type.
The Sequence data types of interest to us are:
    String
    List
    Tuple (similar to lists... like lists for our purposes only immutable)
    Range (similar to lists... list lists for our purposes, only autogenerated)
"""

import suffix_generator


def main():
    print("\nIterating through the characters in a string:")
    for character in "hello":
        print(character)

    print("\nIterating through the numbers in a list:")
    for number in [0, 2, 4, 6, 8]:
        print(number)

    print("\nIterating through the values in a range:")
    for number in range(0, 10, 2):  # very similar to [0, 2, 4, 6, 8]
        print(number)

    print("\nIterating through the values in a range, using suffix generator module:")
    # the variable name 'i' is very often used when iterating through a sequence of integers
    for i in range(30):
        # call our own module's function to determine the correct suffix
        suffix = suffix_generator.generate_ordinal_suffix(i)
        print(f"This is the {i}{suffix} time I'm saying this!")


# run the main function if running this file directly
if __name__ == "__main__":
    main()
